version: '3.7'

networks:
  application:
    driver: bridge

services:
  backend:
    tty: true
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        APP_USER_ID: '${APP_USER_ID}'
        APP_GROUP_ID: '${APP_GROUP_ID}'
    volumes:
      - ${BACKEND_PATH}:/var/www/html
    networks:
      - application
    ports:
      - ${BACKEND_PORT}:80

  frontend:
    tty: true
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ${FRONTEND_PATH}:/usr/src/app
    networks:
      - application
    ports:
      - ${FRONTEND_PORT}:3000
